# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Greeting.destroy_all

Greeting.create([
  { message: 'Hello Wêreld!'},
  { message: 'Përshendetje Botë'},
  { message: 'ሰላም ልዑል!'},
  { message: 'مرحبا بالعالم!'},
  { message: 'Բարեւ աշխարհ!'},
  { message: 'Kaixo Mundua!'},
  { message: 'Прывітанне Сусвет!'},
  { message: 'ওহে বিশ্ব!'},
  { message: 'Здравей свят!'},
  { message: 'Hola món!'},
  { message: 'Moni Dziko Lapansi!'},
  { message: '你好世界！'},
  { message: 'Pozdrav svijete!'},
  { message: 'Ahoj světe!'},
  { message: 'Hej Verden!'},
  { message: 'Hallo Wereld!'},
  { message: 'Hello World!'},
  { message: 'Tere maailm!'},
  { message: 'Hei maailma!'},
  { message: 'Bonjour monde!'},
  { message: 'Hallo wrâld!'},
  { message: 'გამარჯობა მსოფლიო!'},
  { message: 'Hallo Welt!'},
  { message: 'Γειά σου Κόσμε!'},
  { message: 'Sannu Duniya!'},
  { message: 'שלום עולם!'},
  { message: 'नमस्ते दुनिया!'},
  { message: 'Helló Világ!'},
  { message: 'Halló heimur!'},
  { message: 'Ndewo Ụwa!'},
  { message: 'Halo Dunia!'},
  { message: 'Ciao mondo!'},
  { message: 'こんにちは世界！'},
  { message: 'Сәлем Әлем!'},
  { message: 'សួស្តី​ពិភពលោក!'},
  { message: 'Салам дүйнө!'},
  { message: 'ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!'},
  { message: 'Sveika pasaule!'},
  { message: 'Labas pasauli!'},
  { message: 'Moien Welt!'},
  { message: 'Здраво свету!'},
  { message: 'Hai dunia!'},
  { message: 'ഹലോ വേൾഡ്!'},
  { message: 'Сайн уу дэлхий!'},
  { message: 'မင်္ဂလာပါကမ္ဘာလောက!'},
  { message: 'नमस्कार संसार!'},
  { message: 'Hei Verden!'},
  { message: 'سلام نړی!'},
  { message: 'سلام دنیا!'},
  { message: 'Witaj świecie!'},
  { message: 'Olá Mundo!'},
  { message: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!'},
  { message: 'Salut Lume!'},
  { message: 'Привет мир!'},
  { message: 'Hàlo a Shaoghail!'},
  { message: 'Здраво Свете!'},
  { message: 'Lefatše Lumela!'},
  { message: 'හෙලෝ වර්ල්ඩ්!'},
  { message: 'Pozdravljen svet!'},
  { message: '¡Hola Mundo! '},
  { message: 'Halo Dunya!'},
  { message: 'Salamu Dunia!'},
  { message: 'Hej världen!'},
  { message: 'Салом Ҷаҳон!'},
  { message: 'สวัสดีชาวโลก!'},
  { message: 'Selam Dünya!'},
  { message: 'Привіт Світ!'},
  { message: 'Salom Dunyo!'},
  { message: 'Chào thế giới!'},
  { message: 'Helo Byd!'},
  { message: 'Molo Lizwe!'},
  { message: 'העלא וועלט!'},
  { message: 'Mo ki O Ile Aiye!'},
  { message: 'Sawubona Mhlaba!'}
  ])        
